project:
  type: website
  output-dir: docs
  
render:
      - index.qmd
      - 10-API-INTRO.qmd
      - 11-API-OPENDATASOFT.qmd
      - 12-API-INSEE.qmd
      - 20-CARTO-INTRO.qmd
      - 21-CARTO-sf.qmd
      - 22-CARTO-mapsf.qmd  
      - XX-PROJ-Carto1.qmd 
      - 23-Carto-leaflet.qmd  
      
website:
  title: "DataMining2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 10-API-INTRO.qmd
      - 11-API-OPENDATASOFT.qmd
      - 12-API-INSEE.qmd
      - 20-CARTO-INTRO.qmd
      - 21-CARTO-sf.qmd      
      - 22-CARTO-mapsf.qmd   
      - XX-PROJ-Carto1.qmd  
      - 23-Carto-leaflet.qmd 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



